### ISSUE TITLE
Posting an empty list of slugs to /projects/name does not remove them

### ISSUE THREAD

**Issue by iankronquist** [osuosl/timesync-node#162]
If I post to `http://localhost:8851/v1/projects/gwm` to update gwm and my new object has no
slugs, the object in the db after the post has the same slugs it started with. That is, the slugs are not deleted.

This was found with a fuzz tester!

**Comment by iankronquist** [comment]
The relevant section of the docs is pretty bare-bones: https://github.com/osuosl/timesync/blob/develop/source/draft_api.rst#post-projects-slug

**Comment by LyonesGamer** [comment]
If you send a project to ``/projects/<slug>`` without passing a slugs field, the slugs will stay the same (similarly to how, if you don't pass a name, the name will stay the same). If you send an empty array, the slugs field will be set to an empty array.

If this was a problem previously, and not simply poorly-clarified docs, it has been fixed by #174. The docs have been clarified by https://github.com/osuosl/timesync/pull/34.
