### ISSUE TITLE
Profile TimeSync

### ISSUE THREAD

**Issue by iankronquist** [osuosl/timesync-node#189]
The test suite is taking significantly longer to run than it used to, and my gut tells me that it's not just because we have more tests. In fact, after many tests mocha prints out how many milliseconds they took to run. Most tests are now bright red and take ~.1 seconds to run.

We should profile our test suite and see if there are parts which could be improved. It looks like profiling NodeJS code is easy, and this could be a fun and interesting experience.
https://nodejs.org/en/blog/uncategorized/profiling-node-js/

**Comment by LyonesGamer** [comment]
I'm not going to close the issue because I think it may still be worth discussing, but with the introduction of transactions in #191 and #192, we're now running 209 tests in 7s, with the longest test (create a new time) taking 84 ms. I'd personally consider that sufficiently efficient, but I'll leave it open to discussion.
