### ISSUE TITLE
Unexpected server error when updating time

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/timesync-node#270]
When attempting to update a time, status code 500 is returned with the text "Unexpected server error." This happens both with Pymesync and sending raw JSON with cURL.

Example:
```
>>> ts.update_time(uuid='71bf593d-ceeb-4000-87b7-754fca76d10a', time={'date_worked': '2016-05-19'})
{u'status': 500, u'text': u'Unexpected server error.', u'error': u'Server error'}

$ curl -H "Content-Type: application/json" -X POST -d '{"auth":{"type":"token", "token":"the token"}, "object": {"duration":1200}}' http://timesync-staging.osuosl.org/v0/times/71bf593d-ceeb-4000-87b7-754fca76d10a
{"status":500,"error":"Server error","text":"Unexpected server error."}
```

**Comment by LyonesGamer** [comment]
Not able to take too much of a look right now, but the error message from the logs is:

``Error retrieving time to update: TypeError: Cannot read property 'username' of undefined``

**Comment by LyonesGamer** [comment]
Looks like the issue is that there are no times on the server, so you can't update that time. A patch will be needed to improve the error message.3

**Comment by aaroncohen73** [comment]
@LyonesGamer That definitely wasn't the case when I was testing it. It looks like all the times were deleted off of the server (which must have happened over the weekend). The issue is still there, as I just submitted a new time to the server and attempted to update it via the above methods (substituting the UUID of the newly created time) and I still got the same error.

**Comment by LyonesGamer** [comment]
I am able to reproduce the error on the staging server, but not locally.

@aaroncohen73 What account were you using to update the time? Yours, or the admin user?

**Comment by LyonesGamer** [comment]
I am uncertain what the problem was, but after updating the staging server to develop, it seems to have gone away.

**Comment by LyonesGamer** [comment]
Issue has been rediscovered, confirmed, and more information has been found.

There is a typo in the SQL query, wherein it does ``INNER JOIN projectslugs ON projectslugs.id = times.project`` instead of ``INNER JOIN projectslugs ON projectslugs.project = times.project``.

This means that if the time has a project with an ID which a projectslugs row also has (even if it doesn't match that project), the wrong slug is returned (but it is simply checked to ensure that it exists, then discarded, preventing any issues, and also thus passing tests).

Contrarily, if the time has a project with an ID which no projectslugs row has (e.g. if that projectslugs row has been deleted), the inner join causes the query as a whole to return an empty set. The timesync-node server then assumes that the UUID was incorrect and returns a 404 Not Found (previously a 500 Unexpected Server Error because there was no checking for incorrect slugs).
