### ISSUE TITLE
Maintain High Test Coverage

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/timesync-node#81]
This is an ongoing issue to remind us that we need to keep code coverage up.

Testing code coverage in TimeSync can be done by  running the following:
```
$ npm run coverage
[...tests...]
16 passing (6s)

=============================================================================
Writing coverage Writing coverage reports at [/path/to/timesync-node/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 73.42% ( 174/237 )
Branches     : 67.86% ( 38/56 )
Functions    : 55.07% ( 38/69 )
Lines        : 73.42% ( 174/237 )
================================================================================
```
Running ``npm run latte`` will also run coverage tests (in addition to the linter and tests)

**Comment by iankronquist** [comment]
100% is a hell of a high bar. I think that developer time is better spent testing the functionality than chasing statistics. I do think that maintaining ~80% coverage is more reasonable.

**Comment by ElijahCaine** [comment]
Why is striving for 100% coverage not advisable?

I made a point to say ``~100%`` coverage and not ``100%`` coverage. I just want the project to maintain as much coverage as possible. If the project is in heavy development for a long time I can see coverage slip, this issue is a reminder to keep coverage *high*.

I would argue that by saying 80% we are striving for just as arbitrary a statistic just as much as with 100%. We will get coverage to 80% and stop if we set the bar there.

**Comment by tschuy** [comment]
``src/errors.js`` (46% tested):
* The ones that are currently untested will be integration tested once we write tests for POST /times, except for the 500 error.

``src/users.js`` (46% tested):
* This file is in limbo. We probably don't want to dump the database of passwords whenever someone GETs the endpoints, so we need to discuss WHAT this endpoint should look like. Currently, there's nothing in http://timesync.readthedocs.org/en/latest/draft_api.html#get-endpoints about it, so I'll submit a PR to get rid of it and routes.

``src/routes.js`` (60% tested):
* see ``src/users.js`` comments.

``src/times.js`` (70% tested):
* some % will be inaccessible due to being 500 catching, and I don't think there's a way to induce an exception in an arbitrary point in our code with our testing frameworks. This isn't Ruby; we can't load the file as text, sed a line in, reload it, and run it. (I don't know if you could do all of that in Ruby either though.)
* some % will be inaccessible due to being in a multiple-boolean database access kinda thing, where we wait for slugsDone and usersDone, and only execute the return when both are true.
* It looks like we're not testing an endpoint like ``GET times/NaN``. I'll write up a test for that.

``src/activities.js`` (76%) and ``src/projects.js`` (79%):
* see first two points of ``src/times.js``.

**Comment by iankronquist** [comment]
"some % will be inaccessible due to being 500 catching" ~ This sort of a thing is why we shouldn't spend time trying to get 100% coverage. Sure 80% is arbitrary, but there's a difference between arbitrary and unrealistic.

**Comment by LyonesGamer** [comment]
I don't feel that keeping this issue open is relevant or important. I think we all understand that we should maintain high test coverage, and personally, I feel issues should be something resolvable. If we want to remind ourselves that test coverage is important, we should put it in some sort of developer guideline, not a project issue.
